Class {
	#name : #GTDummyExamplesWithSubjects,
	#superclass : #Object,
	#category : #'GT-Examples-Dummies-Set-4'
}

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> a [
	<gtExample>
	<subjectHelp: 'GT Inspector'>
	
	^ 0
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> b [
	<gtExample>
	<subjectHelp: 'GT Inspector' page: 'Roassal'>
	^ 0
	
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> c [
	<gtExample>
	<subjectClass: 'GTExample'>
	^ 0
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> d [
	<gtExample>
	<subjectPackage: 'GT-Examples'>
	^ 0
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> e [
	<gtExample>
	<subjectTag: 'GT-Examples-Dummies-Set-4'>
	^ 0
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> f [
	<gtExample>
	<subjectTag: 'Set-4'>
	^ 0
]

{ #category : #'as yet unclassified' }
GTDummyExamplesWithSubjects >> g [
	<gtExample>
	<subjectClass: 'GTExample' selector: #methodClass>
	<subjectClass: #GTExample selector: #selector>
	<subjectMetaClass: #GTExample selector: #selector>
	<subjectClass: #GTExample selector: #run>
	^ 0
]
