Extension { #name : #ZnStatusLine }

{ #category : #'*GT-Examples-Examples' }
ZnStatusLine class >> gtExampleForbidden [
	<gtExample>
	<label: 'Forbidden'>
	
	^ self forbidden
]

{ #category : #'*GT-Examples-Examples' }
ZnStatusLine class >> gtExampleNotFound [
	<gtExample>
	<label: 'Not Found'>
	
	^ self notFound
]

{ #category : #'*GT-Examples-Examples' }
ZnStatusLine class >> gtExampleOk [
	<gtExample>
	<label: 'Ok'>
	
	^ self ok
]
