Class {
	#name : #GTImplementorsSpotterMock1,
	#superclass : #Object,
	#category : #'GT-Spotter-Tests'
}

{ #category : #public }
GTImplementorsSpotterMock1 >> doSomething [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> doSomethingElse [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> something1 [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> something2 [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> something3 [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> something4 [
]

{ #category : #public }
GTImplementorsSpotterMock1 >> something5 [
]
